language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: microservice-nodejs
  api_key:
    secure: DvxYo6q0jObzlDRK/ugihuXqlfX+n7NdDPb1Qyc8am/tTCDBIjnwYTIwSTM5GFd7s0CeAfNVuVh7fM2e6DGRKSv6HbyLy8Dg5qaZDAyLPjOep//i4HyFtsnFx07UOJ1jEZnIlf6h76yllkvHvmrlrTk7TQHyH5xLa5l0NmWwBikX6wtLTSj7Lf35cbuN77cW8DBLP6NN0uHUnm9aOIUwU1S5QMFqEPZnRyOxbfXgnkBsVH+mYGwrrfu39mdecnjUxiOQpGpp23KlX02zB8IlsFjIvse/U4oC1VgRVCNTPCtd7Xw9FZeqRNq74IYHgbsjk16KCPVQZ913Dr0ozZkMj0yjZkMiotrNH+EJ3Ot1GxPwpSzBg5qpBNQSAJVLgmsqSqrWrcMKpIr5UCsFvfaJEZPMUWAGEReIKRILYJZAQ1f98IIxVMKQKmrH3FDoFoMKQLUtRmCT2nzBmMouVJXZfpHArT7qpIT0K2gjGjd32YH4JBIvncNkY0+ERZcp1sY1clfXzcgQyasa2hoakeK6M0k8XBzVrWbaoa5QIhQqSkS/77HIYSRpBxP4MKE0eLfdAOzwskS1AFTzPoxQd6j0/aZiiWwxLFRpD6tIRcJezj4kNt+BogUuuM/nZdEioKieN2Ywpfkn4jJpqx1uKYU7wZT9fznpKbmBTd/VyIKJbz0=
