language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: microservice-nodejs
  api_key:
    secure: EzMRhFTizxmSV0fqu1CcRiGrPNppVGuQYTQeVVKIU9goC70grrJlWVMzzSdc9tZN55N9rbxw7ybKwZ1kkIkuMKLhS/fGPc1aGDQB8c+DM5z1wheTJ5lICxJ12uWiPW72FMWqiSPL0qJB9C8IZa95v8iLJFupwwFa0UplGevVcFE6eFeLbJ3lnmKyDydqpX1FkAVJo6yl0Wng+aEHNgZkv9yBvzJEO+woWVos8lPnh7AOY+KXw/nep6NfeBen3FCWBJTPpWR1a3iAU0fdUIFcnxiXW8lCehRiLufz9sl3cxc+6HzMqDrf2p9VVJK/Kpbkw6QiVk+9td88IyN4XarV8UQS1D41ELg8g9xbtlmEIlLyiXo6XNi2GnR8UIYLhabpQ1INR7bHSzVCu5duAGck46DFGBQ8OqG2EdvQTyIP/dHoTHs4ZRv85A6wltM1/7M0c+9xjS15WVVZLxfzOAYhSFfGC4yHyUFP7AWjVJbdv9oGp2OT8Mw3pJOKnAUx7w7SMdYpGrFOgCuYjWLpM0qfYeiiRFicCA3xmAPQVLVOW4XMBUfPO7FNU/qKNQhCyw0NMCd3JGpsgvQGazs6hirXTYQHU+xXBt9PNVS9Gc+yhF7NJ9sE+/50e/urOJsn0nN7EXcJBDwn37nFyYoBI1WVyUt0CslMWGAKeGQEKM3itOA=
